# Generated by Django 5.1.1 on 2024-09-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
    ]
