# Generated by Django 5.1.1 on 2024-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_logindata_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Anonymus'), (1, 'Registered')], default=0),
        ),
    ]
