# Generated by Django 5.2 on 2025-04-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_logindata_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindata',
            name='user_type',
        ),
        migrations.AddField(
            model_name='logindata',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
