# Generated by Django 5.2 on 2025-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_remove_logindata_user_type_logindata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Anonymus'), (1, 'Registered')], default=0),
        ),
    ]
